server:
  port: 8080

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

info:
  app:
    name: ${spring.application.name}
    version: 0.0.1-SNAPSHOT


spring:
  application:
    name: Onco Cure Assist
  profiles:
    active: local
  datasource:
    url: #override me
    username: #override me
    password: #override me
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 1
      maximum-pool-size: 30
      connection-timeout: 10000
      idle-timeout: 60000
  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.temp.use_jdbc_metadata_defaults: false
  flyway:
    enabled: true